name: Setup Roswell

on:
  workflow_call:
    inputs:
      lisp:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  setup_roswell:
    name: ${{ github.events.inputs.lisp }} on ${{ github.events.inputs.os }}
    steps:
      - name: Setup MSYS2 if Windows
        if: ${{ startsWith( github.events.inputs.os , 'windows' }}
        uses: msys2/setup-msys2@v2
      - name: Install Roswell
        env:
          LISP: ${{ github.events.inputs.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Add Roswell to Linux/MacOS Path
        if: ${{ startsWith( github.events.inputs.os , 'ubuntu' ) || startsWith( github.events.inputs.os , 'mac' ) }}
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
      - name: Add Roswell to Windows Path
        if: ${{ startsWith( github.events.inputs.os , 'windows' }}
        run: |
          echo /c/Users/runneradmin/.roswell/lisp/quicklisp/bin >> $GITHUB_PATH
